name: youtube_player_iframe_plus
description: Flutter port of the official YouTube iFrame player API. Supports web & mobile platforms with small additions
version: 2.3.2
repository: https://github.com/tuvia/youtube_player_flutter_plus.git
homepage: https://github.com/sarbagyastha/youtube_player_flutter/tree/master/packages/youtube_player_iframe

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
